### ISSUE TITLE
TypeError: Object [object Object] has no method 'attachSchema'

### ISSUE THREAD

**Issue by zammitt** [yogiben/meteor-comments#1]
After running "meteor add yogiben:comments" I get the following error when I try to start meteor.  Any ideas?

My repo is located at https://github.com/zammitt/pinball-scores

```
                                           throw(ex);                                                                                        
W20141106-02:22:38.077(0)? (STDERR)                                                   ^                                                                                           
W20141106-02:22:38.078(0)? (STDERR) TypeError: Object [object Object] has no method 'attachSchema'                                                                                
W20141106-02:22:38.078(0)? (STDERR)     at __coffeescriptShare (packages/yogiben:comments/lib/both/collections.coffee:22:9)                                                       
W20141106-02:22:38.079(0)? (STDERR)     at /home/action/workspace/pinball-scores/.meteor/local/build/programs/server/packages/yogiben_comments.js:67:4                            
W20141106-02:22:38.079(0)? (STDERR)     at /home/action/workspace/pinball-scores/.meteor/local/build/programs/server/packages/yogiben_comments.js:130:3                           
W20141106-02:22:38.079(0)? (STDERR)     at /home/action/workspace/pinball-scores/.meteor/local/build/programs/server/boot.js:168:10                                               
W20141106-02:22:38.080(0)? (STDERR)     at Array.forEach (native)                                                                                                                 
W20141106-02:22:38.080(0)? (STDERR)     at Function._.each._.forEach (/home/action/.parts/packages/meteor/1.0/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web
.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)                                                                                  
W20141106-02:22:38.080(0)? (STDERR)     at /home/action/workspace/pinball-scores/.meteor/local/build/programs/server/boot.js:82:5
```

**Comment by zammitt** [comment]
This even happens by loading up a fresh meteor project and adding only this module.

Maybe upgrading to the latest version of autoform would help?  When I add this project it downgrades my autoform package.  I'm not really sure how to test if this helps (I'm very new to meteor).

**Comment by zammitt** [comment]
I was able to fix this by copying to package to my project and changing aldeed:autoform to version 4.0.0 in the packages.js file.  I also had to add aldeed:collection2 and aldeed:simple-schema.  

https://github.com/zammitt/pinball-scores/blob/master/packages/yogiben:comments/package.js

**Comment by yogiben** [comment]
I added

```
   api.imply('aldeed:simple-schema')
   api.imply('aldeed:collection2')
```

to the package file.
