### ISSUE TITLE
Unable to add it to ta local app

### ISSUE THREAD

**Issue by webmakin** [yogiben/meteor-comments#3]
This is the error i get when i add the package and start my meteor app:

``` javascript
Exited with code: 8
W20141205-11:48:06.205(5.5)? (STDERR)         
W20141205-11:48:06.209(5.5)? (STDERR) /home/asif/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20141205-11:48:06.210(5.5)? (STDERR)                                           throw(ex);
W20141205-11:48:06.210(5.5)? (STDERR)                                                 ^
W20141205-11:48:06.211(5.5)? (STDERR) TypeError: Object [object Object] has no method 'attachSchema'
W20141205-11:48:06.212(5.5)? (STDERR)     at __coffeescriptShare (packages/yogiben:comments/lib/both/collections.coffee:28:9)
W20141205-11:48:06.212(5.5)? (STDERR)     at /home/asif/workspace/cards_frontend/.meteor/local/build/programs/server/packages/yogiben_comments.js:77:4
W20141205-11:48:06.213(5.5)? (STDERR)     at /home/asif/workspace/cards_frontend/.meteor/local/build/programs/server/packages/yogiben_comments.js:140:3
W20141205-11:48:06.213(5.5)? (STDERR)     at /home/asif/workspace/cards_frontend/.meteor/local/build/programs/server/boot.js:168:10
W20141205-11:48:06.213(5.5)? (STDERR)     at Array.forEach (native)
W20141205-11:48:06.214(5.5)? (STDERR)     at Function._.each._.forEach (/home/asif/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141205-11:48:06.214(5.5)? (STDERR)     at /home/asif/workspace/cards_frontend/.meteor/local/build/programs/server/boot.js:82:5
```

List of  Packages my app uses currently:

```
accounts-google     1.0.2  Login service for Google accounts
accounts-twitter    1.0.2  Login service for Twitter accounts
accounts-ui         1.1.3  Simple templates to add login widgets to an app
bootstrap           1.0.1  Front-end framework from Twitter
iron:router         1.0.3  Routing specifically designed for Meteor
jquery              1.0.1  Manipulate the DOM using CSS selectors
meteor-platform     1.2.0  Include a standard set of Meteor packages in your app
meteorhacks:kadira  2.15.2  Performance Monitoring for Meteor
meteorhacks:npm     1.2.1  Use npm modules with your Meteor App
npm-container       1.0.0  Contains all your npm dependencies
sacha:spin          2.0.4  Simple spinner package for Meteor
```

**Comment by yogiben** [comment]
Please update and try again.
